import { CheckCircle2, FileText, Link2, PackageCheck } from 'lucide-react'
import { useMemo, useState } from 'react'
import { phaseLabel } from '../domain/catalog'
import { requirementCoverage } from '../domain/requirements'
import { usePortfolio } from '../state/PortfolioContext'
import type { RequirementStatus } from '../types'

const statusLabels:Record<RequirementStatus,string>={draft:'Rascunho',review:'Em revisão',approved:'Aprovado',in_delivery:'Em execução',delivered:'Entregue',qa_approved:'QA aprovado',client_approved:'Homologado',changed:'Alterado'}
const relevanceLabels={go_live_blocker:'Bloqueia go-live',first_value_required:'Necessário ao 1º valor',non_blocking:'Não bloqueante',future:'Futuro'}

export function RequirementsPage(){const {state,dispatch}=usePortfolio();const [projectId,setProjectId]=useState(state.projects[0]?.id??'');const [selected,setSelected]=useState('');const project=state.projects.find(p=>p.id===projectId)??state.projects[0];const coverage=useMemo(()=>requirementCoverage(project?.requirements??[]),[project]);const requirement=project?.requirements.find(r=>r.id===selected)??project?.requirements[0]
  if(!project)return null
  return <div className="page"><header className="page__header"><div><p className="eyebrow">Rastreabilidade ponta a ponta</p><h1>Requisitos e DRN</h1><p>Da necessidade de negócio à homologação do cliente.</p></div><label className="project-picker">Implantação<select value={project.id} onChange={e=>{setProjectId(e.target.value);setSelected('')}}>{state.projects.map(p=><option value={p.id} key={p.id}>{p.profile.clientName}</option>)}</select></label></header>
    <section className="metrics metrics--compact"><article className="metric"><FileText/><span>Requisitos</span><strong>{coverage.total}</strong><small>DRN versão {project.requirements[0]?.version??'0.1'}</small></article><article className="metric"><PackageCheck/><span>Entregues</span><strong>{coverage.delivered}</strong><small>Concluídos pelo time técnico</small></article><article className="metric"><CheckCircle2/><span>Homologados</span><strong>{coverage.clientApproved}</strong><small>Aceite formal do cliente</small></article><article className="metric metric--danger"><Link2/><span>Bloqueadores abertos</span><strong>{coverage.goLiveBlockersOpen}</strong><small>Requisitos críticos da jornada</small></article></section>
    <div className="split-view"><section className="panel requirement-index"><div className="panel__head"><div><h2>DRN estruturado</h2><p>{project.profile.clientName} · {phaseLabel(project.mainPhase,true)}</p></div></div>{project.requirements.map(req=><button className={requirement?.id===req.id?'is-selected':''} onClick={()=>setSelected(req.id)} key={req.id}><span><b>{req.code}</b><small>{req.title}</small></span><em>{statusLabels[req.status]}</em></button>)}</section>
      {requirement&&<section className="panel requirement-detail"><div className="trace-title"><span>{requirement.code} · v{requirement.version}</span><h2>{requirement.title}</h2><div><b>{relevanceLabels[requirement.relevance]}</b><b>{requirement.conditional?'Condicional':'Núcleo padrão'}</b></div></div><div className="trace-chain"><article><small>1 · Necessidade</small><p>{requirement.businessNeed}</p></article><article><small>2 · Regra de negócio</small><p>{requirement.businessRule}</p></article><article><small>3 · Critério de aceite</small><p>{requirement.acceptanceCriteria}</p></article><article><small>4 · Evidência</small><p>{requirement.testIds.length} teste(s) vinculado(s) · validador: {requirement.validator}</p></article></div><label className="status-control">Atualizar estado do requisito<select value={requirement.status} onChange={e=>dispatch({type:'requirement/status',projectId:project.id,requirementId:requirement.id,status:e.target.value as RequirementStatus})}>{Object.entries(statusLabels).map(([id,label])=><option value={id} key={id}>{label}</option>)}</select><small>A alteração é simulada e pode ser restaurada a qualquer momento.</small></label></section>}
    </div></div>}
