import { ArrowRight, CalendarClock, GitPullRequestArrow, Plus } from 'lucide-react'
import { FormEvent, useState } from 'react'
import { phaseLabel } from '../domain/catalog'
import { usePortfolio } from '../state/PortfolioContext'
import type { ScopeChange, ScopeChangeStatus, ScopeChangeType } from '../types'

const typeLabels:Record<ScopeChangeType,string>={defect:'Defeito',requirement_divergence:'Divergência de requisito',scope_change:'Mudança de escopo',future_improvement:'Melhoria futura',configuration_pending:'Configuração pendente'}
const statusLabels:Record<ScopeChangeStatus,string>={analysis:'Em análise',awaiting_client:'Aguardando cliente',approved:'Aprovada',rejected:'Recusada',planned_future:'Planejada para o futuro'}
export function ScopeChangesPage(){const {state,dispatch}=usePortfolio();const [projectId,setProjectId]=useState(state.projects[0]?.id??'');const [open,setOpen]=useState(false);const project=state.projects.find(p=>p.id===projectId)??state.projects[0];const [draft,setDraft]=useState({title:'',description:'',type:'scope_change' as ScopeChangeType,impactDays:3,impactsGoLive:false});const changes=project.scopeChanges??[]
  const submit=(e:FormEvent)=>{e.preventDefault();const now=new Date().toISOString();const change:ScopeChange={id:`${project.id}-change-${Date.now()}`,code:`MUD-${String(changes.length+1).padStart(3,'0')}`,title:draft.title,description:draft.description,type:draft.type,status:'analysis',requestedBy:'Visitante do protótipo',impactPhase:project.mainPhase,impactDays:draft.impactDays,impactsGoLive:draft.impactsGoLive,createdAt:now,updatedAt:now};dispatch({type:'change/add',projectId:project.id,change});setOpen(false);setDraft({title:'',description:'',type:'scope_change',impactDays:3,impactsGoLive:false})}
  return <div className="page"><header className="page__header"><div><p className="eyebrow">Controle de mudança</p><h1>Mudanças de escopo</h1><p>Classificação, impacto e decisão sem perder a linha de base.</p></div><div className="page__actions"><label className="project-picker">Implantação<select value={project.id} onChange={e=>setProjectId(e.target.value)}>{state.projects.map(p=><option value={p.id} key={p.id}>{p.profile.clientName}</option>)}</select></label><button className="button button--primary" onClick={()=>setOpen(!open)}><Plus size={16}/> Nova análise</button></div></header>
    {open&&<form className="panel change-form" onSubmit={submit}><label>Título<input required value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>Classificação<select value={draft.type} onChange={e=>setDraft({...draft,type:e.target.value as ScopeChangeType})}>{Object.entries(typeLabels).map(([id,label])=><option value={id} key={id}>{label}</option>)}</select></label><label className="span-2">Descrição<textarea required value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></label><label>Impacto estimado em dias<input min="0" type="number" value={draft.impactDays} onChange={e=>setDraft({...draft,impactDays:Number(e.target.value)})}/></label><label className="inline-check"><input type="checkbox" checked={draft.impactsGoLive} onChange={e=>setDraft({...draft,impactsGoLive:e.target.checked})}/> Pode impactar o go-live</label><footer className="span-2"><button type="button" className="button button--secondary" onClick={()=>setOpen(false)}>Cancelar</button><button className="button button--primary">Registrar para análise</button></footer></form>}
    <section className="change-summary"><article><GitPullRequestArrow/><span><strong>{changes.length}</strong> solicitações</span></article><article><CalendarClock/><span><strong>{changes.filter(c=>c.impactsGoLive).length}</strong> com impacto no go-live</span></article></section>
    <section className="change-list">{changes.map(change=><article className="panel" key={change.id}><header><span>{change.code} · {typeLabels[change.type]}</span><b>{statusLabels[change.status]}</b></header><h2>{change.title}</h2><p>{change.description}</p><div className="impact-flow"><span>Linha de base</span><ArrowRight/><span>{phaseLabel(change.impactPhase,true)}</span><ArrowRight/><strong>+{change.impactDays} dia(s){change.impactsGoLive?' · afeta go-live':''}</strong></div><footer><label>Decisão<select value={change.status} onChange={e=>dispatch({type:'change/status',projectId:project.id,changeId:change.id,status:e.target.value as ScopeChangeStatus})}>{Object.entries(statusLabels).map(([id,label])=><option value={id} key={id}>{label}</option>)}</select></label></footer></article>)}{!changes.length&&<div className="empty-inline">Nenhuma mudança registrada. Use “Nova análise” para testar o fluxo.</div>}</section>
  </div>}
