import { CircleCheck, CircleX, FlaskConical, ShieldCheck } from 'lucide-react'
import { useMemo, useState } from 'react'
import { evaluateGoLiveGate } from '../domain/gates'
import { usePortfolio } from '../state/PortfolioContext'
import type { TestResult } from '../types'

const resultLabel:Record<TestResult,string>={not_run:'Não executado',approved:'Aprovado',failed:'Reprovado',approved_with_note:'Aprovado com ressalva'}
export function TestsPage(){const {state,dispatch}=usePortfolio();const [projectId,setProjectId]=useState(state.projects[0]?.id??'');const [type,setType]=useState<'all'|'internal'|'client'>('all');const project=state.projects.find(p=>p.id===projectId)??state.projects[0];const tests=useMemo(()=>project.tests.filter(t=>type==='all'||t.type===type),[project,type]);const gate=evaluateGoLiveGate(project);const counts=project.tests.reduce((a,t)=>{const r=t.executions.at(-1)?.result??'not_run';a[r]=(a[r]??0)+1;return a},{} as Record<TestResult,number>)
  return <div className="page"><header className="page__header"><div><p className="eyebrow">Qualidade e aceite</p><h1>Testes e homologação</h1><p>QA interno e UAT do cliente conectados ao mesmo requisito.</p></div><label className="project-picker">Implantação<select value={project.id} onChange={e=>setProjectId(e.target.value)}>{state.projects.map(p=><option value={p.id} key={p.id}>{p.profile.clientName}</option>)}</select></label></header>
    <section className={`gate-banner ${gate.ready?'is-ready':'is-blocked'}`}><span>{gate.ready?<ShieldCheck/>:<CircleX/>}</span><div><strong>{gate.ready?'Gate de go-live liberado':'Gate de go-live requer decisão'}</strong><p>{gate.ready?'Critérios críticos atendidos no cenário atual.':gate.reasons.join(' · ')}</p></div><small>O alerta não bloqueia sua navegação.</small></section>
    <section className="test-summary"><div><FlaskConical/><span><strong>{project.tests.length}</strong> casos</span></div><div><CircleCheck/><span><strong>{counts.approved??0}</strong> aprovados</span></div><div><CircleX/><span><strong>{counts.failed??0}</strong> reprovados</span></div><nav><button className={type==='all'?'is-active':''} onClick={()=>setType('all')}>Todos</button><button className={type==='internal'?'is-active':''} onClick={()=>setType('internal')}>QA interno</button><button className={type==='client'?'is-active':''} onClick={()=>setType('client')}>UAT cliente</button></nav></section>
    <section className="test-grid">{tests.map(test=>{const last=test.executions.at(-1);return <article className="panel test-card" key={test.id}><header><span>{test.code} · {test.type==='internal'?'QA interno':'UAT cliente'}</span><b className={`result result--${last?.result??'not_run'}`}>{resultLabel[last?.result??'not_run']}</b></header><h2>{test.title}</h2><p><strong>Resultado esperado:</strong> {test.expectedResult}</p>{last&&<small>Última execução por {last.executor} em {new Date(last.executedAt).toLocaleDateString('pt-BR')}</small>}<footer><button onClick={()=>dispatch({type:'test/execute',projectId:project.id,testId:test.id,result:'approved',executor:test.type==='client'?project.profile.clientKeyUser:'Equipe de QA'})}>Registrar aprovação</button><button onClick={()=>dispatch({type:'test/execute',projectId:project.id,testId:test.id,result:'failed',executor:test.type==='client'?project.profile.clientKeyUser:'Equipe de QA'})}>Registrar falha</button></footer></article>})}</section>
  </div>}
